version: '3.9'
services:
  postgres:
    networks:
      - backend
  spring-boot:
    networks:
      - frontend
      - backend
  nginx:
    image: dimmaryanto93/udemy-angular-app:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_VERSION=14.15-alpine
        - NGINX_VERSION=latest
        - APPLICATION_NAME=docker-angular
    ports:
      - "80:80"
    environment:
      - APPLICATION_PORT=80
      - NGINX_ROOT_DOCUMENT=/var/www/html
      - BACKEND_HOST=spring-boot
      - BACKEND_PORT=8080
      - BACKEND_CONTEXT_PATH=/
    networks:
      - frontend
    depends_on:
      - spring-boot
networks:
  frontend:
  backend