version: '3.9'
services:
  postgres:
    image: postgres:14.2
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=kirahadian12
      - POSTGRES_USER=rizki
      - POSTGRES_PASSWORD=12345678
    volumes:
      - pg_data:/var/lib/postgresql/data
  spring-boot:
    image: dimmaryanto93/udemy-springboot-app:latest
    ports:
      - "8080:8080"
    environment:
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_NAME=kirahadian12
      - DATABASE_USER=rizki
      - DATABASE_PASSWORD=12345678
      - APPLICATION_PORT=8080
    depends_on:
      - postgres
volumes:
  pg_data:
